#pragma once
#include "common.h"
#include "ad.h"

const string reasons[] = {
	"CONTEXT_CHANGE_REASON_FATALSIGNAL",
	"CONTEXT_CHANGE_REASON_SIGNAL",
	"CONTEXT_CHANGE_REASON_SIGRETURN",
	"CONTEXT_CHANGE_REASON_APC",
	"CONTEXT_CHANGE_REASON_EXCEPTION",
	"CONTEXT_CHANGE_REASON_CALLBACK"
};
